language: python
python:
  - "3.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run

before_deploy:
  - git config --global user.name "Caffreyfans"
  - git config --global user.email "Caffreyfans@163.com"
  - mkdir tmp && cd tmp
  - cp ../.pio/build/esp8266-1m*/firmware.bin IRbaby1m.bin
  - cp ../.pio/build/esp8266-2m*/firmware.bin IRbaby2m.bin
  - cp ../.pio/build/esp8266-4m*/firmware.bin IRbaby4m.bin
  - zip -q IRbaby.zip *

deploy:
  provider: releases
  file_glob: true
  api_key: ${GITHUB_TOKEN}
  file: 
    - IRbaby.zip
  skip_cleanup: true
  on:
    tags: true